/**
 * This code was generated by Builder.io.
 */
import { NgModule } from "@angular/core";
import { CommonModule } from "@angular/common";
import { SendFlowComponent } from "./send-flow.component";
import { SidebarComponent } from "./sidebar/sidebar.component";
import { HeaderComponent } from "./header/header.component";
import { ProgressBarComponent } from "./progress-bar/progress-bar.component";
import { ReceiptComponent } from "./receipt/receipt.component";

@NgModule({
  declarations: [
    SendFlowComponent,
    SidebarComponent,
    HeaderComponent,
    ProgressBarComponent,
    ReceiptComponent,
  ],
  imports: [CommonModule],
  exports: [SendFlowComponent],
})
export class SendFlowModule {}
