/**
 * This code was generated by Builder.io.
 */
import { Component } from "@angular/core";
import { ProgressBarComponent } from "./progress-bar/progress-bar.component";
import { ReceiptComponent } from "./receipt/receipt.component";
import { SidebarComponent } from "./sidebar/sidebar.component";
import { HeaderComponent } from "./header/header.component";

@Component({
  selector: "app-send-flow",
  standalone: true,
  imports: [ProgressBarComponent, ReceiptComponent, SidebarComponent, HeaderComponent],
  templateUrl: "./send-flow.component.html",
  styleUrls: ["./send-flow.component.css"],
})
export class SendFlowComponent {
  // Component logic here
}
